slam_node:
  ros__parameters:
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"

    kiss_slam:
      local_mapper:
        voxel_size: 0.2
        splitting_distance: 5.0

      occupancy_mapper:
        free_threshold: 0.5
        occupied_threshold: 0.7
        resolution: 0.2
        max_range: -1.0   # -1.0 = null
        z_min: 0.1
        z_max: 0.5

      mapping:
        voxel_size: -1.0   # -1.0 = null
        max_points_per_voxel: 20

      loop_closer:
        detector:
          density_map_resolution: 0.2
          density_threshold: 0.05
          hamming_distance_threshold: 50
          inliers_threshold: 5
        overlap_threshold: 0.4

      pose_graph_optimizer:
        max_iterations: 10
